services:
  braui-v1:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: braui-v1:production
    container_name: braui-v1-production
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - braui-v1-network

networks:
  braui-v1-network:
    driver: bridge
